### ISSUE TITLE
Why δ(vi-vj) is O(KD)?

### ISSUE THREAD

**Issue by artofstate** [POSTECH-CVLab/FastPointTransformer#3]
Hi!
When I read your paper at reducing space complexity section, it says that the space complexity of δrel(vi-vj) is O(KD),I can't understand it.
I think there are K neighbors for each voxel,why not O(IKD)? I hope you can help me ,Thanks!

**Comment by chrockey** [comment]
Hi,

Thank you for your interest in our work.

> I think there are K neighbors for each voxel, why not O(IKD)?

Although there are K neighbors for each voxel (`v_i`), each `v_i - v_j` must be one of K different relative positions since `v_i` is regular (or voxel coordinate). Therefore, we only need a shared look-up table, whose space complexity is O(KD), to represent all of `δ_rel(v_i - v_j)`.
You may find the look-up table is defined in the following code line:
https://github.com/POSTECH-CVLab/FastPointTransformer/blob/4272a69464da19e5cebcd66314fe6e0d59d19624/src/models/fast_point_transformer.py#L68

Hope this helps your understanding.

**Comment by moshicaixi** [comment]
> Hi! When I read your paper at reducing space complexity section, it says that the space complexity of δrel(vi-vj) is O(KD),I can't understand it. I think there are K neighbors for each voxel,why not O(IKD)? I hope you can help me ,Thanks!

my understanding is (3X3 window as an example, where K=8):
    centroid point: (i, j)
    neighbor point, from left to right and top to bottom: (i-1, j-1), (i, j-1), (i+1, j-1), (i-1, j), (i+1, j), (i-1, j+1), (i, j+1), (i+1, j+1)
for all points, there are only the above 8 relative positional relation.

**Comment by auniquesun** [comment]
> Hi,
> 
> Thank you for your interest in our work.
> 
> > I think there are K neighbors for each voxel, why not O(IKD)?
> 
> Although there are K neighbors for each voxel (`v_i`), each `v_i - v_j` must be one of K different relative positions since `v_i` is regular (or voxel coordinate). Therefore, we only need a shared look-up table, whose space complexity is O(KD), to represent all of `δ_rel(v_i - v_j)`. You may find the look-up table is defined in the following code line:
> 
> https://github.com/POSTECH-CVLab/FastPointTransformer/blob/4272a69464da19e5cebcd66314fe6e0d59d19624/src/models/fast_point_transformer.py#L68
> 
> Hope this helps your understanding.

I am confused why a shared lookup table can work for all `v_i - v_j`. 
In my opinion, a shared lookup table can only work for current `v_i` and all its neighbors. You need to create another lookup table for another `v_i`. Therefore, the space time complexity of `δ(v_i - v_j)` should be O(IKD) rather than O(KD). Further, it implies the proposed local self-attention increases space complexity.
