### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by zouwenqin** [POSTECH-CVLab/FastPointTransformer#4]
Thanks for the great work! I have some questions.
1. I wonder where the GPU memory budget cost in FastTrans. Because I only have GTX1080, 12G. Do you test the model for small-scale task like ShapeNet DataSet? And can I apply the lightweight self-attention to get a better feature embedding for ShapeNet classification in my 1080 machine? Maybe I can use a smaller FastTrans?
2. I notice that the voxel size is used for data augmention. If i use the model for ShapeNet classification which normalized coordinates lie between -1 and 1. Can I remove the data augmention and just use original coordinates? Or how to get a feasible voxel size ?

**Comment by YuanYunshuang** [comment]
Hi, according to my understanding of the paper and the code, I would do the following regarding your questions:
1. maybe just try reducing the batch size or decreasing the attention layers or channels? 
2. I think the dimensionless coordinates are related to the kernel parameters in the Minkovski Engine. The author uses kernel_stride=1, and kernel_size=3, which means the receptive field in each layer is 3*voxel_size, i.e. 3x0.02=0.06m according to the settings in the default config file. Since the Minkovski Engine only takes in the integer type for the kernel parameters as arguments, you may still need the dimensionless coordinates for your experiments.

I hope this could help...

**Comment by chrockey** [comment]
Hi @zouwenqin,

Sorry for the late reply.

> Do you test the model for small-scale task like ShapeNet DataSet?

I did not try Fast Point Transformer on small-scale datasets (e.g., ModelNet, ScanObjectNN, ShapeNet, ...). If you want to try it, you can reduce the voxel size to use a finer voxel resolution than the one used for large-scale scenes.

> Maybe I can use a smaller FastTrans?

As @YuanYunshuang commented, you may build a smaller Fast Point Transformer by reducing the number of attention layers or the feature dimension.

> Can I remove the data augmention and just use original coordinates?

Yes. However, I recommend you to check out the ModelNet40 classification example of MinkowskiEngine (https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/classification_modelnet40.py), first.

> Or how to get a feasible voxel size ?

I'm not sure which voxel size is suitable for ShapeNet. You may find one through visualization of the voxelized coordinates.

**Comment by zouwenqin** [comment]
@chrockey @YuanYunshuang ,Thank for reply firstly.
1. I train the original Fast Point Transformer architecture for feature extraction on ShapeNet dataset, which batch size set 32 and point number set 2048.  I remove the data augmention so that i can ignore the voxel size. However, I get a similar result as the Point Transformer, but the training time of Fast Trans is longer than Point Trans (10 minute one epoch for Fast Trans and  almost 9 minute for Point Trans). I'm confused about the training speed.
2. I have some question in the voxelize with centroids code. I mark it as below. How can I control the resolution of voxelized point cloud without data augmentation. It seem like I got a fixed resolution.
![image](https://user-images.githubusercontent.com/66156211/169819543-55ce2da9-2e98-47db-8258-870bd13dc3e3.png)

**Comment by chrockey** [comment]
> the training time of Fast Trans is longer than Point Trans (10 minute one epoch for Fast Trans and almost 9 minute for Point Trans)

In the small point cloud scheme, Fast Point Transformer may not benefit from voxel hashing since the k-nearest neighbor search is fast enough for that size of point clouds. Moreover, the training time contains the backward-pass time, where our custom CUDA operations can be further optimized.

> How can I control the resolution of voxelized point cloud without data augmentation

For the `MinkowskiEngine.TensorField.sparse` function, you may refer to the original repo:

https://github.com/NVIDIA/MinkowskiEngine/blob/2f31bc51e0abdf89ed20730e531480df1b2cc64a/MinkowskiEngine/MinkowskiTensorField.py#L286

For the voxelization, you can divide the original coordinates by your own voxel size, using the DimensionlessCoordinates transform or just dividing the voxel size directly. For example, if you want 1024 * 1024 * 1024 voxel resolution with normalized coordinates in [-1, 1), your voxel size would be 2/1024. As I mentioned before, you can visualize the voxelized coordinates to find a proper voxel size for your own dataset.
