### ISSUE TITLE
how to download the dataset?

### ISSUE THREAD

**Issue by ZoangX** [POSTECH-CVLab/FastPointTransformer#6]
Before calling the script preprocess_s3dis.py,I need to download the data manually, right? Or automatic download in the script  preprocess_s3dis.py? If I need to download it automatically,How to download the dataset?

**Comment by chrockey** [comment]
Hi,

> Before calling the script preprocess_s3dis.py, I need to download the data manually, right?

Yes. You need to download the original dataset before running the preprocessing.
For the S3DIS dataset, you can refer [this link](http://buildingparser.stanford.edu/dataset.html).

**Comment by ZoangX** [comment]
Thank you.
I'm not going to lie, I'm a novice in this area. I see that in other deep networks, such as PointNet, the data is downloaded and organized automatically. Can you fill in the code for the previous part of automatic download and organization like other networks?
Because this is difficult for me, partly because I am a novice, and partly because your codes has few comments.
Thank you very much!

**Comment by chrockey** [comment]
Hi @ZoangX,

Sorry for the late reply.
I cannot provide download scripts since some datasets (e.g., ScanNet) have their own policy to release the dataset.
Here are helpful links for you to refer to:
- [ScanNet dataset](https://github.com/ScanNet/ScanNet): You need to fill out the Terms of Use.
- [S3DIS dataset](http://buildingparser.stanford.edu/dataset.html#Download): You need to fill out the google forms.
